---
name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest
    strategy:
      matrix:
        PYTHON_VERSION:
#          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - uses: actions/checkout@v4
      - run: |
          python -m pip install poetry~=1.8.4
          poetry install --no-ansi
      - run: just tests
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.PYTHON_VERSION }}_robot_log
          path: log.html
